#!/bin/sh

## 起動前に実行したいコマンドをここに追加します。

babel src/*.js > app/index.es5.js

## wwwディレクトリの内容をChrome Appとして起動します。
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --load-and-launch-app=`pwd`/app
